### ISSUE TITLE
Trojan Virus in Butler-SOS

### ISSUE THREAD

**Issue by Justformoment** [ptarmiganlabs/butler-sos#447]
### What version of Butler SOS are you using?

9.2.2

### What version of Node.js are you using? Not applicable if you use the standalone version of Butler SOS.

N/A

### What command did you use to start Butler SOS?

N\A

### What operating system are you using?

N\A

### What CPU architecture are you using?

N\A

### What Qlik Sense versions are you using?

N\A

### Describe the Bug

Hi Team,

During the scan for virus in virustotal.com, we have found trojan virus in it. Can you check or confirm if it's false positive?
![image](https://user-images.githubusercontent.com/26446355/195803149-4569f7b0-70c0-4893-8a77-f2309f826499.png)

Thank you all

**Comment by mountaindude** [comment]
@Justformoment thanks for reporting this.

You didn't mention which OS you use, but I have scanned the Windows and macOS binaries using both Bitdefender (macOS + Windows) and Windows Defender (Windows). 

All scans came back negative.

Now, there are two options:
1. Your antivirus software is correct and Bitdefender + Windows Defender is incorrect. In that case there's a malware.
2. Bitdefender + Windows Defender is correct. No malware.

I can't  guarantee that there isn't a problem, but as only 1 of 62 scanners (funny - when I ran the scan I got reply from 69 scanners) in VirusTotal reports the file as malicious I am personally not too worried.

**Comment by mountaindude** [comment]
We've done a few more releases of both Butler SOS and other tools since this ticket was created, and that same scanner always report the Butler family as virus/malware. Everyone else says its fine.

Could be because Butler, Butler SOS and their siblings are all Node.js apps wrapped up to become Windows EXE files. 
Maybe that scanner doesn't like that. Just a guess..

Closing this ticket as we can't find anything solid to work on.
